pipeline {
    agent {
        docker {
            image 'docker.desaysv.com/ici2/tools/maven-edoc:20240112'
            args '-v /root/.m2:/root/.m2'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage("Clone code from github") {
            steps {
                script {
                    git credentialsId: 'wangzhaokai', url: 'git@github.com:wangzhaokai11/simple-java-maven-app.git'
                }
            }
        }
        stage("Compile Build") {
            steps {
                echo "This is a non-parallel stage in Compile Build"
                // 第一个步骤
                sh "mvn package -DskipTests=true"
                archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true 
                // 第二个步骤
                echo "This is another non-parallel stage in Compile Build"
                sh "wget https://edoc-1316692706.cos.ap-guangzhou.myqcloud.com/edoc.tar.gz"
                // 第三个步骤
                echo "This is yet another non-parallel stage in Compile Build"
                sh "wget https://github.com/kingToolbox/WindTerm/archive/refs/tags/2.5.0.tar.gz"
                // 更多步骤...
            }
        }
        stage("Compile Build-1") {
            parallel {
                stage("cpile-parallel-1") {
                    steps {
                        echo "This is a non-parallel stage in cpile-parallel-1"
                        // 此处添加相应的步骤
                    }
                }
                stage("cpile-parallel-2") {
                    steps {
                        echo "This is a non-parallel stage in cpile-parallel-2"
                        // 此处添加相应的步骤
                    }
                }
                // 更多并行步骤...
            }
        }
        stage("Compile Build-2") {
            steps {
                script {
                    echo "This is a non-parallel stage in Compile Build-2"
                    // 此处添加相应的步骤
                }
            }
        }
        stage("Publish to Edoc Repository Manager") {
            when {
                expression {
                    currentBuild.result == null || currentBuild.result == 'SUCCESS'
                }
            }
            parallel {
                stage("edoc执行") {
                    steps {
                        script {
                            echo "This is a non-parallel stage in edoc执行"
                            // 此处添加相应的步骤
                        }
                    }
                }
                stage("并行执行") {
                    steps {
                        script {
                            echo "This is a non-parallel stage in 并行执行"
                            // 此处添加相应的步骤
                        }
                    }
                }
            }
        }
        stage("Finish") {
            steps {
                script {
                    echo "流水线执行完成"
                }
            }
        }
    }
}
