pipeline {
    agent {
        docker {
            image 'docker.desaysv.com/ici2/tools/maven-edoc:20240112'
            args '-v /root/.m2:/root/.m2'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage("Clone code from github") {
            steps {
                script {
                    git credentialsId: 'wangzhaokai', url: 'git@github.com:wangzhaokai11/simple-java-maven-app.git'
                }
            }
        }
        stage("Compile Build") {
            steps {
                echo "This is a non-parallel stage in Compile Build"
                sh "mvn package -DskipTests=true"
                archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true 
            }
        }
        stage("Compile Build-1") {
            stages {
                stage("Serial Sub-stage 1") {
                    steps {
                        echo "This is a serial sub-stage in Compile Build-1"
                        // 添加相应的步骤
                    }
                }
                stage("Serial Sub-stage 2") {
                    steps {
                        echo "This is another serial sub-stage in Compile Build-1"
                        // 添加相应的步骤
                    }
                }
            }
        }
        stage("Compile Build-2") {
            steps {
                script {
                    echo "This is a non-parallel stage in Compile Build-2"
                    // 添加相应的步骤
                }
            }
        }
        stage("Publish to Edoc Repository Manager") {
            when {
                expression {
                    currentBuild.result == null || currentBuild.result == 'SUCCESS'
                }
            }
            parallel {
                stage("edoc执行") {
                    steps {
                        script {
                            echo "This is a non-parallel stage in edoc执行"
                            // 添加相应的步骤
                        }
                    }
                }
                stage("并行执行") {
                    stages {
                        stage("Sub-stage 1") {
                            steps {
                                echo "This is a sub-stage in 并行执行"
                                // 添加相应的步骤
                            }
                        }
                        stage("Sub-stage 2") {
                            steps {
                                echo "This is another sub-stage in 并行执行"
                                // 添加相应的步骤
                            }
                        }
                    }
                }
            }
        }
        stage("Finish") {
            steps {
                script {
                    echo "流水线执行完成"
                }
            }
        }
    }
}
