pipeline {
    agent {
        docker {
            image 'docker.desaysv.com/ici2/tools/maven-edoc:20240112'
            args '-v /root/.m2:/root/.m2'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage("Clone code from github") {
            steps {
                script {
                    git credentialsId: 'wangzhaokai', url: 'git@github.com:wangzhaokai11/simple-java-maven-app.git'
                }
            }
        }
        stage("Compile Build") {
            parallel {
                stage("cpile-parallel-1") {
                    stages {
                        stage("sub-para-1-1-MCU") {
                            steps {
                                script {
                                    sh "mvn package -DskipTests=true"
                                    archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true 

                }
                            }
                        }
                        stage("sub-para-1-2-XXX") {
                            steps {
                                echo "This is another sub-stage in 并行执行"
                              // sh "wget https://github.com/kingToolbox/WindTerm/releases/download/2.5.0/WindTerm_2.5.0_Mac_Portable_x86_64.dmg"
                            }
                        }
                    }
                }
                stage("cpile-parallel-2") {
                    stages {
                        stage("sub-para-2-1-QNX") {
                            steps {
                                script {

                    // echo '执行edoc上传'
                    def tarFile = "./edoc.tar.gz"
                    def downloadNeeded = !fileExists(tarFile)

                    // 如果文件不存在，则下载
                    if (downloadNeeded) {
                        sh "wget https://edoc-1316692706.cos.ap-guangzhou.myqcloud.com/edoc.tar.gz"
                    }
                    sh "tar -zxvf edoc.tar.gz"

                    dir('edoc'){
                    sh "ls"
                    sh "./pipeline-edoc.sh wangzkjenkins 1377193 ${env.WORKSPACE}/target/my-app-1.0-SNAPSHOT.jar ${env.WORKSPACE}"
                               }
                }}
                            }
                        
                        stage("sub-para-2-2-CCC") {
                            steps {
                                echo "This is another sub-stage in 并行执行"
                               // sh "wget https://github.com/kingToolbox/WindTerm/releases/download/2.5.0/WindTerm_2.5.0_Windows_Portable_x86_64.zip"
                                dir('edoc'){
                                sh "ls"
                                sh "./single-edoc.sh only_create_folder wangzktest011119 1377193"
                               }
                            }
                        }
                        stage("sub-para-2-3-MMM") {
                            steps {
                                echo "This is another sub-stage in 并行执行"
                             //  sh "wget https://github.com/kingToolbox/WindTerm/archive/refs/tags/2.5.0.zip"
                                dir('edoc'){
                                sh "ls"
                                sh "./single-edoc.sh only_upload ${env.WORKSPACE}/target/my-app-1.0-SNAPSHOT.jar 1377193"
                            }
                        }
                    }}
                
                stage("cpile-parallel-3") {
                    steps {
                        echo "This is a sub-stage in 并行执行"
                       // sh "wget https://github.com/kingToolbox/WindTerm/archive/refs/tags/2.5.0.tar.gz"
                    }
                }
              stage("cpile-parallel-4") {
                    stages {
                        stage("sub-para-4-1-APP") {
                            steps {
                                echo "This is a sub-stage in 并行执行"
                              //  sh "wget https://github.com/kingToolbox/WindTerm/releases/download/2.5.0/WindTerm_2.5.0_Linux_Portable_x86_64.tar.gz"
                            }
                        }
                        stage("sub-para-4-2-AN") {
                            steps {
                                echo "This is another sub-stage in 并行执行"
                             //    sh "wget https://github.com/kingToolbox/WindTerm/releases/download/2.5.0/WindTerm_2.5.0_Mac_Portable_x86_64.dmg"
                            }
                        }
                    }
                }  
            }}
                stage("Compile Build-4") {
                    steps {
                        echo "编译构建串行无并"
                    //    sh "wget https://edoc-1316692706.cos.ap-guangzhou.myqcloud.com/edoc.tar.gz"
                    }
                }
            
        
        stage("Publish to Edoc Repository Manager") {
            when {
                expression {
                    currentBuild.result == null || currentBuild.result == 'SUCCESS'
                }
            }
            parallel {
                stage("edoc执行") {
                    steps {
                        script {
                            echo "This is a non-parallel stage in edoc执行"
                            // 添加相应的步骤
                        }
                    }
                }
                
            
        
        stage("并行执行") {
                    steps {
                        echo "This is a sub-stage in 并行执行"
                        // 添加相应的步骤
                    }
                }}}
        stage("Finish") {
            steps {
                script {
                    echo "流水线执行完成"
                }
            }
        }
    }}
